from sqlalchemy.orm import Session
from models import Violation


def generate_report(db: Session):

    total = db.query(Violation).count()

    helmet = db.query(Violation).filter(
        Violation.helmet == False
    ).count()

    vest = db.query(Violation).filter(
        Violation.vest == False
    ).count()

    danger = db.query(Violation).filter(
        Violation.zone == "Danger"
    ).count()

    report = f"""
====================================
 SafeSite AI Daily Report
====================================

Total Records : {total}

Helmet Violations : {helmet}

Vest Violations : {vest}

Danger Zone Entries : {danger}

Generated by SafeSite AI
"""

    return report